create table if not exists places (
  id text primary key,
  name text not null,
  slug text unique not null,
  category text not null,
  location text,
  latitude double precision,
  longitude double precision,
  description text,
  image text,
  opening_time text,
  closing_time text,
  best_season text,
  specialty text,
  entry_fee text,
  visit_duration text
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  place_id text not null,
  rating integer not null check (rating between 1 and 5),
  review text not null,
  created_at timestamptz default now()
);

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  place_id text not null,
  created_at timestamptz default now()
);

create table if not exists restaurants (
  id text primary key,
  name text not null,
  location text,
  cuisine text,
  price text,
  rating numeric,
  latitude double precision,
  longitude double precision,
  image text
);

alter table places enable row level security;
alter table reviews enable row level security;
alter table favorites enable row level security;
alter table restaurants enable row level security;

create policy "public read places" on places for select using (true);
create policy "public read restaurants" on restaurants for select using (true);
create policy "public read reviews" on reviews for select using (true);
create policy "public insert reviews" on reviews for insert with check (true);
