insert into places
(id,name,slug,category,location,latitude,longitude,description,image,opening_time,closing_time,best_season,specialty,entry_fee,visit_duration)
values
('vivekananda-rock','Vivekananda Rock Memorial','vivekananda-rock-memorial','Historical','Kanyakumari',8.080953,77.551343,'A landmark memorial built in honour of Swami Vivekananda on a rocky island off the coast of Kanyakumari.','https://commons.wikimedia.org/wiki/Special:FilePath/Vivekananda%20Rock%20Memorial,%20Kanyakumari.jpg','8:00 AM','4:00 PM','October – March','Offshore memorial, ferry ride and sunrise views.','Boat service / entry varies','1–2 hours'),
('thiruvalluvar-statue','Thiruvalluvar Statue','thiruvalluvar-statue','Historical','Kanyakumari',8.078081,77.55506,'The monumental statue of Tamil poet and philosopher Thiruvalluvar stands on a rocky island off Kanyakumari.','https://commons.wikimedia.org/wiki/Special:FilePath/Kavi%20Thiruvalluvar%20Statue.jpg','8:00 AM','4:00 PM','October – March','133-foot statue and sea views.','Boat service / entry varies','1 hour'),
('thirparappu-waterfalls','Thirparappu Waterfalls','thirparappu-waterfalls','Waterfalls','Thirparappu',8.391111,77.259444,'The Kodayar River descends at Thirparappu to form a broad seasonal waterfall and popular recreation spot.','https://commons.wikimedia.org/wiki/Special:FilePath/Thiruparappu%20falls%2001.jpg','7:00 AM','6:00 PM','June – January','Waterfall, river and surrounding greenery.','₹5 listed by district site','1–2 hours'),
('padmanabhapuram-palace','Padmanabhapuram Palace','padmanabhapuram-palace','Historical','Padmanabhapuram',8.250916,77.326702,'A major heritage palace complex known for timber architecture, murals, carved interiors and historic collections.','https://commons.wikimedia.org/wiki/Special:FilePath/Padmanabhapuram%20Palace(1).jpg','9:00 AM','4:30 PM','October – March','Wooden architecture, murals and royal heritage.','₹35 adult; ₹10 child; camera ₹50 (district listing)','1.5–2 hours'),
('mathoor-aqueduct','Mathoor Aqueduct','mathoor-aqueduct','Nature','Mathoor',8.344959,77.295644,'Built in 1966, the Mathoor Aqueduct carries a water trough across a valley on tall pillars and is a distinctive engineering landmark.','https://commons.wikimedia.org/wiki/Special:FilePath/Mathur%20aqueduct.jpg','6:30 AM','6:30 PM','October – March','Long elevated aqueduct and valley views.','Check local listing','1 hour'),
('vattakottai-fort','Vattakottai Fort','vattakottai-fort','Historical','Kanyakumari',8.12576,77.56527,'A coastal fort overlooking the sea, built as part of the historic defensive network of the region.','https://commons.wikimedia.org/wiki/Special:FilePath/Vattakottai%20Fort%20Inside.jpg','8:00 AM','5:00 PM','October – March','Sea-facing fort walls and coastal views.','Check local listing','1 hour'),
('suchindram-temple','Thanumalayan Swamy Temple','thanumalayan-swamy-temple','Temples','Suchindram',8.1551,77.4658,'A prominent temple dedicated to the combined form of Brahma, Vishnu and Shiva, with elaborate carvings and a rich architectural tradition.','https://commons.wikimedia.org/wiki/Special:FilePath/Thanumalayan%20Temple,%20Suchindram.jpg','4:30 AM','8:30 PM','October – March','Musical pillars, sculptures and towering gopuram.','Free entry; special services may vary','1–2 hours'),
('pechiparai-dam','Pechiparai Dam','pechiparai-dam','Dams','Pechiparai',8.45137,77.30782,'A historic irrigation reservoir in the Western Ghats, known for its landscape and viewpoints around the water body.','https://commons.wikimedia.org/wiki/Special:FilePath/Pechiparai%20dam.JPG','Daylight hours','Daylight hours','October – March','Reservoir, hills and scenic countryside.','No standard tourist fee listed','1–2 hours'),
('kumari-amman-temple','Kumari Amman Temple','kumari-amman-temple','Temples','Kanyakumari',8.0793,77.551,'A major pilgrimage landmark at the southern tip of India, associated with the goddess Kanya Kumari.','https://commons.wikimedia.org/wiki/Special:FilePath/Kanyakumari%20Temple.JPG','Morning and evening worship hours','See temple notice','October – March','Coastal pilgrimage temple and Kanyakumari heritage.','Free entry; special services may vary','45–90 min'),
('muttom-beach','Muttom Beach','muttom-beach','Beaches','Muttom',8.120997,77.319783,'A scenic coastal destination known for rocky shorelines, sea views and a lighthouse area nearby.','https://commons.wikimedia.org/wiki/Special:FilePath/Muttom%20Beach.JPG','Open area','Open area','October – March','Rocky coastline and sunset views.','Free beach access','1–2 hours'),
('sunrise-point','Sunrise Point','sunrise-point','Beaches','Kanyakumari',8.08547,77.55317,'A popular seafront viewpoint near the southern tip of India where visitors watch sunrise over the surrounding seas.','https://commons.wikimedia.org/wiki/Special:FilePath/Kanyakumari%20sunrise.jpg','Before sunrise','Open public area','October – March','Sunrise and southernmost coastal views.','Free public viewpoint','30–60 min'),
('glass-bridge','Kanyakumari Glass Bridge','kanyakumari-glass-bridge','Historical','Kanyakumari',8.07905,77.55345,'The Kanyakumari Glass Bridge connects the Vivekananda Rock Memorial and Thiruvalluvar Statue across the sea. The district administration says it was inaugurated on December 30, 2024 and is 77 metres long and 10 metres wide.','https://cdn.s3waas.gov.in/s38fe0093bb30d6f8c31474bd0764e6ac0/uploads/2025/05/2025052077.png','8:00 AM','4:00 PM','October – March','Sea bridge with views of Vivekananda Rock and Thiruvalluvar Statue.','Ferry/bridge access varies','30–60 min'),
('gandhi-mandapam','Gandhi Mandapam','gandhi-mandapam','Historical','Kanyakumari',8.07881,77.54996,'A memorial at the Kanyakumari seafront commemorating Mahatma Gandhi. Its architecture is designed so that sunlight falls on the memorial''s central spot around October 2.','https://commons.wikimedia.org/wiki/Special:FilePath/Gandhi%20Mandapam,%20Kanyakumari.jpg','Daytime','Evening','October – March','Historic memorial and coastal viewpoint.','Check local listing','30–60 min'),
('kamaraj-memorial','Kamaraj Memorial','kamaraj-memorial','Historical','Kanyakumari',8.0801,77.5493,'A seafront memorial dedicated to K. Kamarajar, a freedom fighter and former Chief Minister of Tamil Nadu. The district administration lists public hours from 7 AM to 7 PM.','https://commons.wikimedia.org/wiki/Special:FilePath/Kamarajar%20Memorial,%20Kanyakumari,%20Tamilnadu%2001.jpg','7:00 AM','7:00 PM','October – March','Kamarajar memorial and seafront setting.','Check local listing','30–60 min'),
('kovalam-beach-kk','Kovalam Beach, Kanyakumari','kovalam-beach-kanyakumari','Beaches','Kovalam',8.091465,77.518486,'Kovalam Beach in Kanyakumari district is a coastal destination with golden sand, gentle waves and views around the southern tip of India.','https://commons.wikimedia.org/wiki/Special:FilePath/Kovalam%20beach%20kanyakumari.JPG','Open public area','Open public area','October – March','Golden-sand beach and sunset views.','Free beach access','1–2 hours'),
('nagaraja-temple','Sri Nagaraja Temple','sri-nagaraja-temple','Temples','Nagercoil',8.187617,77.43313,'A major temple in Nagercoil associated with Nagaraja worship, with a complex preserving Hindu and older Jain-influenced iconography.','https://commons.wikimedia.org/wiki/Special:FilePath/Nagaraja%20temple,%20Nagercoil,%20Tamil%20Nadu%20India%20-%208.jpg','Morning and evening worship hours','See temple notice','October – March','Nagaraja shrine and distinctive temple architecture.','Free entry; special services may vary','1 hour'),
('chittar-dam','Chittar Dam','chittar-dam','Dams','Chittar',8.435,77.253333,'Chittar Dam II is an important tourist place in Kanyakumari district. The district administration describes it as an earthen dam constructed during 1964–1969.','https://commons.wikimedia.org/wiki/Special:FilePath/Chittar%20dam%20reservoir.jpg','Daylight hours','Daylight hours','October – March','Reservoir, dam engineering and rural landscape.','No standard tourist fee listed','1 hour'),
('kalikesam','Kalikesam','kalikesam','Nature','Kalikesam',8.410967,77.391467,'Kalikesam combines evergreen forest, river scenery and a riverside Kali temple. The district administration lists timings of 9 AM to 3 PM for the spot.','https://commons.wikimedia.org/wiki/Special:FilePath/Kalikesam.jpg','9:00 AM','3:00 PM','October – January','Forest, river bathing area and Kali temple.','Forest/eco-tourism charges may apply','2–3 hours'),
('kodayar-twin-falls','Kodayar Twin Falls','kodayar-twin-falls','Waterfalls','Veerapuli Reserve Forest',8.478,77.355,'Kodayar Twin Falls is a scenic twin-stream waterfall in the Veerapuli Reserve Forest. The district administration describes the falls as plunging from around 200 feet amid dense greenery.','https://commons.wikimedia.org/wiki/Special:FilePath/Kodayar%20river,%20Kanyakumari%20district.jpg','Daylight / local forest access','Daylight / local forest access','Monsoon and post-monsoon','Twin waterfall and dense Western Ghats forest.','Check forest/eco-tourism rules','2–3 hours')
on conflict (id) do update set
name=excluded.name, slug=excluded.slug, category=excluded.category, location=excluded.location,
latitude=excluded.latitude, longitude=excluded.longitude, description=excluded.description,
image=excluded.image, opening_time=excluded.opening_time, closing_time=excluded.closing_time,
best_season=excluded.best_season, specialty=excluded.specialty, entry_fee=excluded.entry_fee,
visit_duration=excluded.visit_duration;
